DROP TABLE IF EXISTS Member;
DROP TABLE IF EXISTS Club;
DROP TABLE IF EXISTS GroupsCourse;
DROP TABLE IF EXISTS TeacherCourse;
DROP TABLE IF EXISTS Student;
DROP TABLE IF EXISTS Course;
DROP TABLE IF EXISTS Groups;
DROP TABLE IF EXISTS People;
