DROP TABLE IF EXISTS Marks;
DROP TABLE IF EXISTS Plan;
DROP TABLE IF EXISTS Clubs;
DROP TABLE IF EXISTS Students;
DROP TABLE IF EXISTS Groups;
DROP TABLE IF EXISTS Lecturers;
DROP TABLE IF EXISTS Courses;
DROP TABLE IF EXISTS  ClubMembers;