
DROP FUNCTION IF EXISTS RegisterUser;
DROP FUNCTION IF EXISTS FindUserByPass;
DROP FUNCTION IF EXISTS CanBuyFromNow;
DROP FUNCTION IF EXISTS CanReserveFromNow;
DROP FUNCTION IF EXISTS ThisSeatIsEmpty;
DROP FUNCTION IF EXISTS CheckReservationExpiry;
DROP PROCEDURE IF EXISTS CheckReservationExpiry;
DROP FUNCTION IF EXISTS ManageFlight;
DROP FUNCTION IF EXISTS FreeSeats;
DROP FUNCTION IF EXISTS Reserve;
DROP FUNCTION IF EXISTS ExtendReservation;
DROP FUNCTION IF EXISTS BuyFree;
DROP FUNCTION IF EXISTS BuyReserved;
DROP FUNCTION IF EXISTS FlightsStatistics;
DROP FUNCTION IF EXISTS FlightStat;
DROP FUNCTION IF EXISTS CompressSeats;
DROP FUNCTION IF EXISTS IsAdmin;
