st = set()
with open('raw_data.tsv', 'r', encoding='utf-8') as f:
    flag = False
    for line in f:
        if flag:

            data_ = line.lower().split('\t')[8][1:-1].split(',')
            data = []
            for s in data_:
                data.extend([j.strip() for j in s.split('/')])
            st.update(data)
        else:
            flag = True

print(st)

set_of_types = {'cценовый релиз от codex', 'папка с игрой (microsoft store)', 'папка установленной игры (egs)', 'repack от xatab', 'repack (лицензии)', 'origin-rip', 'лицензия + crack (reloaded)', 'лицензия от gog.com', 'лицензия', 'портативная версия в архиве', 'неофициальный rip', 'сценовый релиз от cpy', 'сценовый релиз от plaza', 'архив', 'папка с игрой.', 'repack', 'лицензия (бука)', 'папка с игрой (uplay)', 'папка установленной игры (uplay-rip)', 'egs-rip', 'релиз от gog', 'сценовый релиз от codex', 'папка установленной игры (steam)', 'папка с игрой (steam)', 'папка с игрой', 'папка установленной игры', 'цифровая лицензия gog.com', 'gog-rip + моды в портативной версии', 'cценовый релиз от skidrow', 'steam-rip', 'cценовый релиз от prophet', 'релиз от gog.com', 'портативная версия в архиве (steam)', 'папка игры'}
set_of_genres = {'2021 года', '2018 года', '2012 года', '2016 года', 'action', 'simulation', 'arcade', '2013 года', 'лицензии', 'fighting', 'vr игры', '2014 года', 'horror', '2020 года', '2015 года', '2023 года', '1st person', '2022 года', 'торрент игры', '3d', '2024 года', '2017 года', 'gog', 'strategy', 'stealth', 'adventure', 'оффлайн', 'racing', 'simulator', 'rpg', '3rd person', 'real-time', '2019 года', 'quest', 'shooter', 'decepticon'}

set_of_languages = {'китайский (трад.)', '中文(简体)', 'polski', '', 'испанский (+ латиноамериканский)', 'английский + русификатор по желанию', 'словацкий', 'чешский +11', 'английский |multi8', 'французский', 'японский', 'китайский (упрощённый)', 'испанский', 'ελληνικά', 'китайский упрощённый', 'русский (russian only!)', 'العربية', '日本語', 'испанский + мод-русификатор', 'испанский (2)', 'китайский (2 варианта)', 'português do brasil', 'русский (only!)', 'немецкий + русификатор', 'норвежский', 'китайский (упр.)', 'португальский (+ бразильский)', 'deutsch', 'традиционный китайский', 'белорусский', 'португальский', 'немецкий', 'svenska', 'english (only!)', 'aнглийский', 'english +11', 'арабский', 'китайский простой', '+24', '+16', 'китайский + русификатор', 'китайский (оба)', 'французски', 'русский с модом expansion', 'португальский (2)', 'английский |multi', 'multi7', 'multi', 'multi10', 'português', 'multi + русификатор [1c]', '+11', '한국어 + русификатор', 'английский + русификатор', 'индонезийский', 'türkçe', 'русский через mod.io в настройках меню', 'португальский (бразилия)', 'французский + русификатор', 'китайский (упрощённый + традиционный)', '+15', 'multi3', 'английский + русский (отдельной установкой)', 'english', 'rus|eng|multi', 'italiano 日本語', 'чешский', 'шведский', 'китайский традиционный', 'каталанский', 'турецкий', 'датский', 'norsk', 'английский', 'multi14', 'pусский', 'японский + русский отдельно', 'итальянский', 'испанский латиноамериканский', 'multi13', 'русский | английский', 'русификатор', 'nederlands', '2 варианта)', 'русский', 'english +7', 'китайский (простой)', 'español (al)', 'rus', 'польский', 'multi12', 'français', 'dansk', 'multi11', '中文(简体', 'rus|eng|multi6', 'румынский', 'португальский (+бразильский)', 'китайский (два варианта)', 'italiano', 'română', 'венгерский', 'türkçe + русификатор', 'английский |multi9', 'multi5', 'испанский (латиноам.)', 'упрощенный китайский', 'suomi', 'multi20', 'китайский (2)', 'español', 'русский (отдельно', 'český', '+12', 'португальский - бразилия', '한국어', 'португальский (бр.)', 'english + русификатор', 'английский |multi6', 'бразильский португальский', 'корейский', 'multi25', 'киайский', 'испанский + латиноамериканский', 'персидский', '中文', 'yкраїнська', 'тайский', 'португальский (бразильский)', 'нидерландский', 'китайский', 'испанский лат. ам.', '+9', 'хинди', 'португальский бразильский', 'українська', '+8', 'multi27', 'rus|eng', 'magyar', 'бр. португальский', '中文(繁體)', 'испанский - испания', 'русский; английский; немецкий; французский; итальянский; испанский; португальский; польский; турецкий; японский; корейский; китайский упрощённый', 'multi8', 'украинский', 'english + русификаторы', 'русский|английский', 'китайский (оба варианта)', 'китайский (трад.) + русификатор', 'multi23', 'rus|eng|multi9'}
set_of_voice_languages = {'арабский', 'отсутствует (не требуется)', 'китайский упрощённый', 'español', 'бразильский португальский', 'german', 'português', 'английский\\немецкий', 'العربية', 'český', 'португальский (+ бразильский)', '中文(繁體)', '-', 'русский (в dlc отсутствует)', 'deutsch', 'французский', 'украинский', 'english', 'испанский', '-||-', 'multi7', 'английский', 'итальянский', 'китайский(упр.)', 'английский |multi', 'chinese', 'испанский (2)', 'бр. португальский', 'english + русификаторы', 'korean', 'английский + русификатор', '日本語', '中文(简体)', 'español (al)', 'eng', 'portuguese – brazil', 'português do brasil', 'никакой', 'китайский (упр.)', 'japanese', 'multi', 'magyar', '한국어', 'multi11', 'italiano', 'орейский', 'чешский', 'українська', 'турецкий', 'нет', 'русский (only!)', 'polish', 'английский\\японский', 'русификатор', 'датский', 'русский', 'японский + отдельный русификатор на базе исходной локализации от «1с»', 'китайский (трад.)', 'türkçe', 'тайский', 'русский|английский', 'multi4', 'английский + русский (отдельной установкой)', 'french', 'испанский (+ латиноамериканский)', 'непереводимый', 'eng|jpn', 'немецкий', 'spanish', 'italian', 'français', 'португальский бразильский', 'корейский', 'испанский лат. ам.', 'польский', 'английский  (dlc не все озвучены на русском)', 'rus|eng', 'английский\\польский', 'английский | японский', 'русский (mass effect 1)', 'китайский', 'polski', 'отсутствует', 'японский'}
set_of_tablets = {'вшита [anonymous]', 'вшита', 'delusional', 'smart steam emu', 'blizzless', 'не требуется (drm free от gog)', 'prophet', 'vitality', '3dm', 'вшита (cpy+codex)', 'mr_goldberg + coldclientloader от rat431', 'ali', 'cpy + fixes', 'empress | goldberg', 'присутствует', 'skidrow', 'coldapi от rat431', 'вшита (ali213)', 'darksiders', 'goldberg steam emu. + steamless', 'codex + machine4578', 'нет', 'codex+steamless', 'вшита (3dm', 'codex emu + steamless', 'codex', 'empress-mr.goldberg', 'есть активация', 'empress', 'flt + steamless', 'орейский', 'vrex', 'doge', 'вшита (cpy)', 'онлайн-обход защиты от [0xdeadc0de]', 'mr_goldberg steam emu', 'вшита (skidrow crackfix v2 + codex)', 'steamemu', 'ali213 + 3dm + lumaemu (в архиве)', 'reloaded', 'paradox', 'rune emu + modified exe (от christsnatcher)', 'empress + goldberg steam emu.', 'rune (по умолчанию)', 'не требуется (игра без защиты)', 'mr_goldberg+sse', 'присутствует {prophet}', 'присутствует (reloaded)', 'fairlight', 'польский', '@c0000005', 'английский', 'вшита [reloaded]', 'вшита (plaza)', 'не требуется (drm-free )', 'codex emu + steamless exe', 'plaza', 'online-fix', 'codex- crackfix', 'codex emu', 'не требуется (drm-free от gog)', 'goldberg + steamless', 'rune emu (по умолчанию)', 'codex | fairlight', 'delusional + codex uplay emu', 'mr_goldberg emu+steamless+sse', 'cpy', 'не требуется {drm-free}', 'drm-free', 'бр. португальский', 'mr_goldberg', 'эмулятор steam ali213', 'rune + steamless', 'cdx)', 'вшита {reloaded}', 'rune +steamless', 'присутствует {codex}', 'mr_goldberg (отдельно)', 'steam fix', 'goldberg emu+sse', 'fairlight & custom launcher', 'mr_goldberg emu + steamless', 'ali213 emu. | reloaded emu', 'baldman v3 +codex emu', 'присутствует (skidrow)', 'rune', 'tenoke + steamless', 'не требуется (drm-free)', 'merumeru', 'goldberg emu', 'codex|rune', 'tenoke', 'codex (установлена по умолчанию)', 'присутствует (codex)', 'theta.v 1.04', 'вшита (3dm)', 'mr.goldberg', 'вшита (reloaded)', 'origin emulator: cpy', 'не требуется', 'не требуется {drm free}', 'турецкий', 'rune emu', 'codex (по умолчанию)', 'tinyiso', 'ali213', 'использован steamless [atom0s]', 'nemirtingas epic emu.', 'mr.goldberg + steamless', 'flt', 'codex emu (по умолчанию)', 'goldberg steam emu', 'goldberg', 'steam emu', 'empress|mr_goldberg', 'flt+steamless', 'flt (по умолчанию)', 'codex + christsnatcher', 'не требуется (gog)', 'вшита (codex)', 'rune emu + steamless'}
