DROP TABLE IF EXISTS Mark;
DROP TABLE IF EXISTS GroupCourse;
DROP TABLE IF EXISTS Course;
DROP TABLE IF EXISTS Lecturer;
DROP TABLE IF EXISTS Club;
DROP TABLE IF EXISTS Student;
DROP TABLE IF EXISTS Groups;